 [settings]
max_list_size   = 1000
total_quota     = 300000
max_workers     = 5
request_timeout = [5, 25]
scrub_targets   = [
    "Base", "Pro++", "Ultimate", "Normal", "Social", 
    "Block:", "Allow:", "L_", "ProMini", "ProPlus", 
    "ProUser", "ProHome", "Piracy", "DynDNS", "Hoster", 
    "Restrictive", "Blocked_IPs", "L_SpamTLD", "L_ExtraPorn",
    "L_Piracy", "L_BypassPrevent"
]
auto_enable_rules = true

[tld]
url = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/spam-tlds-onlydomains.txt"

# Standalone Cloudflare Gateway Firewall Policies
[gateway_policies]
"SafeSearch"         = true
"Global Blocklist"   = true
"Global Bypass"      = true
"IoT Bypass"         = true
"Block IoT Network"  = true
"Restrict YouTube"   = true

[sources]
#"HaGeZi Pro"               = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro-onlydomains.txt"
"HaGeZi Pro++"             = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro.plus-onlydomains.txt"
#"HaGeZi Ultimate"          = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/ultimate-onlydomains.txt"
#"HaGeZi Fake"              = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/fake-onlydomains.txt"
#"HaGeZi TIF Full"          = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif-onlydomains.txt"
"HaGeZi Normal"            =  "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/multi-onlydomains.txt"
"HaGeZi Social"            = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/social-onlydomains.txt"
"HaGeZi No SafeSearch"     = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/nosafesearch-onlydomains.txt"
"HaGeZi Bypass Prevention" = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/doh-vpn-proxy-bypass-onlydomains.txt"
"HaGeZi Anti Piracy"       = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/anti.piracy-onlydomains.txt"
#"HaGeZi DynDNS"            = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/dyndns-onlydomains.txt"
#"NoAI"                     = "https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/refs/heads/main/noai_hosts.txt"

"Hagezi NSFW" = [
    "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/nsfw-onlydomains.txt",
    "https://raw.githubusercontent.com/sjhgvr/oisd/refs/heads/main/abp_nsfw.txt"
]

[ip_sources]
# Hijacked Subnets & Bulletproof Transit
"Spamhaus DROP"         = "https://www.spamhaus.org/drop/drop.txt"
"Spamhaus DROPv6"       = "https://www.spamhaus.org/drop/dropv6.txt"

# Active Malware C2 & Botnet Controllers
#"Feodo C2 IPs"          = "https://feodotracker.abuse.ch/downloads/ipblocklist.txt"
#"ThreatFox IOC IPs"     = "https://raw.githubusercontent.com/elliotwutingfeng/ThreatFox-IOC-IPs/main/ips.txt"
#"ET Compromised IPs"    = "https://rules.emergingthreats.net/blockrules/compromised-ips.txt"
#"ET Emerging Block IPs" = "https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt"

# Curated C2 & Threat Aggregates
"HaGeZi TIF IPs"        = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/ips/tif.txt"
#"Binary Defense"        = "https://www.binarydefense.com/banlist.txt"
#"CINS Army"             = "https://cinsscore.com/list/ci-badguys.txt"
"IPsum Level 3"         = "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt"

[spam_allow_source]
name = "HaGeZi Spam Allow"
url  = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/spam-tlds-allow-onlydomains.txt"

[policies.relaxed]
prefix              = "L_Relaxed"
name                = "AdBlock HaGeZi Normal"
action              = "block"
type                = "DOMAIN"
use_spam_tld        = false
include             = [
    "HaGeZi No SafeSearch", "HaGeZi Normal"    
]
exclude             = []
security_categories = []
content_categories  = []

[policies.restrictive]
prefix              = "L_Restrictive"
name                = "Adblock HaGeZi Pro++"
action              = "block"
type                = "DOMAIN"
restrict_users      = true
use_spam_tld        = false
include             = [
    "HaGeZi Pro++", "HaGeZi Social"
]
exclude             = ["HaGeZi Normal"]
security_categories = []
content_categories  = [67, 125]
app_ids             = [
    534, 541, 572, 600, 604, 618, 628, 633, 1110, 1122, 1130, 1135, 1138,
    1853, 2678, 2680, 2826, 2831, 2844, 2845, 2848, 2852, 3097, 3098
]
domains             = ["web.archive.org", "steamcommunity.com", "linkvertise.com", "vercel.com", "rumble.com"]

[policies.blocked_ips]
prefix              = "L_Blocked_IPs"
name                = "Block: Malicious Resolved IPs"
action              = "block"
type                = "IP"
include             = [
    "Spamhaus DROP",
    "Spamhaus DROPv6",
    #"Feodo C2 IPs",
    #"ThreatFox IOC IPs",
    #"ET Compromised IPs",
    #"ET Emerging Block IPs",
    "HaGeZi TIF IPs",
    #"Binary Defense",
    #"CINS Army",
    "IPsum Level 3"
]
exclude             = []

[policies.spamtld]
prefix              = "L_SpamTLD"
name                = "HaGeZi Spam TLD"
action              = "block"
type                = "DOMAIN"
use_spam_tld        = true
include             = []
exclude             = []
security_categories = []
content_categories  = []

[policies.pornblock]
prefix              = "L_ExtraPorn"
name                = "Porn Block"
action              = "block"
type                = "DOMAIN"
use_spam_tld        = false
include             = ["Hagezi NSFW"]
exclude             = []
security_categories = []
content_categories  = [2, 67, 125, 133]

[policies.piracyblock]
prefix              = "L_Piracy"
name                = "Piracy Block"
action              = "block"
type                = "DOMAIN"
use_spam_tld        = false
include             = ["HaGeZi Anti Piracy"]
exclude             = []
security_categories = []
content_categories  = [138]

[policies.BypassPrevention]
prefix              = "L_BypassPrevent"
name                = "Bypass Prevention"
action              = "block"
type                = "DOMAIN"
use_spam_tld        = false
include             = ["HaGeZi Bypass Prevention"]
exclude             = []
security_categories = [68]
content_categories  = []
